package com.ase.bytealchemists.service;

import com.ase.bytealchemists.model.ServiceEntity;
import com.ase.bytealchemists.repository.ServiceRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Service class for managing operations related to services in the Homeless Support API.
 *
 * @author Jason
 * @version 1.0
 */
@Service
public class ServiceService {
  @Autowired
  private ServiceRepository serviceRepository;

  /**
   * Queries services based on latitude, longitude, category, and availability
   * within a fixed radius.
   *
   * <p>This method uses a fixed radius of 10 km to find services within a certain location
   * and applies additional filters such as service category and availability. It calls the
   * repository layer to retrieve the results.</p>
   *
   * @param latitude the latitude to filter services by location
   * @param longitude the longitude to filter services by location
   * @param category the category of services to filter (optional)
   * @param availability the availability status to filter services (optional)
   * @return a list of {@link ServiceEntity} that match the given filters
   */
  public List<ServiceEntity> queryServices(Double latitude, Double longitude,
                                           String category, Boolean availability) {
    double fixedRadius = 10.0;
    return serviceRepository.findByFilters(latitude, longitude,
        fixedRadius, category, availability);
  }


  /**
   * Deletes a service by its ID.
   *
   * @param id the ID of the service to delete
   * @return true if the service was successfully deleted, false if the service was not found
   */
  public boolean deleteServiceById(Long id) {
    if (serviceRepository.existsById(id)) {
      serviceRepository.deleteById(id);
      return true;
    } else {
      return false;
    }
  }

  /**
   * Updates the service entity with the specified ID using the provided service data.
   * Only the non-null fields in the {@code service} object will be updated.
   *
   * @param id      the ID of the service to update
   * @param service the service data containing the fields to be updated
   * @return the updated {@link ServiceEntity} if the service exists, otherwise {@code null}
   */
  public ServiceEntity updateService(Long id, ServiceEntity service) {
    Optional<ServiceEntity> optionalService = serviceRepository.findById(id);
    if (optionalService.isPresent()) {
      ServiceEntity existingService = optionalService.get();

      if (service.getName() != null) {
        existingService.setName(service.getName());
      }
      if (service.getCategory() != null) {
        existingService.setCategory(service.getCategory());
      }
      if (service.getLatitude() != null) {
        existingService.setLatitude(service.getLatitude());
      }
      if (service.getLongitude() != null) {
        existingService.setLongitude(service.getLongitude());
      }
      if (service.getAddress() != null) {
        existingService.setAddress(service.getAddress());
      }
      if (service.getCity() != null) {
        existingService.setCity(service.getCity());
      }
      if (service.getState() != null) {
        existingService.setState(service.getState());
      }
      if (service.getZipcode() != null) {
        existingService.setZipcode(service.getZipcode());
      }
      if (service.getContactNumber() != null) {
        existingService.setContactNumber(service.getContactNumber());
      }
      if (service.getOperationHour() != null) {
        existingService.setOperationHour(service.getOperationHour());
      }
      if (service.getAvailability() != null) {
        existingService.setAvailability(service.getAvailability());
      }

      // Save the updated entity
      return serviceRepository.save(existingService);
    } else {
      return null;
    }
  }


  /**
   * Registers a new service entity in the database.
   * This method saves the provided service entity to the database
   * using the service repository. It returns the saved entity, which
   * includes any autogenerated fields (like the ID).
   *
   * @param serviceEntity the service entity to be registered, containing
   *                      details such as name, category, and location.
   * @return the saved ServiceEntity with any autogenerated fields
   *         populated.
   */
  public ServiceEntity registerService(ServiceEntity serviceEntity) {
    return serviceRepository.save(serviceEntity);
  }

  /**
   * Retrieves all services for all categories.
   *
   * @return a list of all {@link ServiceEntity}
   */

  public List<ServiceEntity> getAllServices() {
    return serviceRepository.findAll();
  }

  /**
   * Retrieves a service by its id.
   *
   * @param id the id of the service to retrieve
   * @return an Optional containing the service entity if found, or empty if not found
   */

  public Optional<ServiceEntity> getServiceById(Long id) {
    return serviceRepository.findById(id);
  }

}
