# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Postman

on:
  push:
    branches: [ "main", "FinishCI" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Newman
        run: npm install -g newman
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run JUnit tests with Maven
        run: mvn test
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: target/site/jacoco/jacoco.xml
          reporttypes: HtmlInline;Cobertura;TextSummary
          sourcedirs: src/main/java/com/ase/bytealchemists
          title: JaCoCo code coverage report
      - name: JaCoCoSummary
        run: cat coveragereport/Summary.txt
      - name: Run PMD Static Analysis
        run: mvn pmd:check || true
      - name: Run Postman Tests
        run: |
          cd postman
          newman run COMS4156_GroupProject_postman_collection.json